server:
  port: 31001
spring:
  application:
    name: cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
